# cloudbuild.yaml
# Build a Docker image and push it to Google Container Registry

# Replace values when creating the trigger or use substitutions
# Example image path: asia-suth1-docker.pkg.dev/PROJECT_ID/demo-app/demo-repo:tag

steps:
# 1) Build image(using docker building)
  - name: 'grc.io/cloud-builders/docker'
    args:
      [
      'build',
      '-t',
      'west2-docker.pkg.dev/stately-forest-480020/python-app-imageeurope/app-image:v1',
      '.'
      ]
# 2) Push image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'west2-docker.pkg.dev/stately-forest-480020/python-app-imageeurope/app-image:v1'
      ]
images:
  - 'west2-docker.pkg.dev/stately-forest-480020/python-app-imageeurope/app-image:v1'


options:
  logging: CLOUD_LOGGING_ONLY

