steps:
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "SCloud Build Triggered Successfully!"
        echo "Repository name: $REPO_NAME"
        echo "Branch name: $BRANCH_NAME"
#options:
#  logging: CLOUD_LOGGING_ONLY

logsBucket: gs://gcp-devops-cert-bucket